apiVersion: apps/v1
kind: Deployment
metadata:
  name: kalandula
  annotations:
    kubernetes.io/change-cause: "First release kalandula"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kalandula
  template:
    metadata:
      labels:
        app: kalandula
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: kalandula
      - maxSkew: 1
        topologyKey: node
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: kalandula
      containers:
      - name: kalandula
        image: 6037159/jenkins-test:latest
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP

